using Atoll.Lagoon.Configuration;

namespace Atoll.Lagoon.Navigation;

/// <summary>
/// Builds a resolved sidebar navigation tree from <see cref="DocsConfig"/> sidebar configuration
/// and a set of content entries.
/// </summary>
/// <remarks>
/// <para>
/// The builder processes each top-level <see cref="SidebarItem"/> from the configuration:
/// <list type="bullet">
///   <item>Leaf items (with <see cref="SidebarItem.Link"/>) become link nodes.</item>
///   <item>Group items (with <see cref="SidebarItem.Items"/> children) are resolved recursively.</item>
///   <item>Auto-generate items (with <see cref="SidebarItem.AutoGenerate"/>) are populated
///         from the provided <see cref="SidebarEntry"/> collection matching the configured directory.</item>
/// </list>
/// </para>
/// <para>
/// The current path is matched against each item's <see cref="ResolvedSidebarItem.Href"/>
/// (case-insensitive, with or without trailing slash) to determine the active item.
/// </para>
/// </remarks>
public sealed class SidebarBuilder
{
    private readonly IReadOnlyList<SidebarItem> _config;
    private readonly IReadOnlyList<SidebarEntry> _entries;

    /// <summary>
    /// Initializes a new instance of <see cref="SidebarBuilder"/>.
    /// </summary>
    /// <param name="config">The sidebar item configuration from <see cref="DocsConfig.Sidebar"/>.</param>
    /// <param name="entries">Content entries used to populate auto-generated groups.</param>
    public SidebarBuilder(IReadOnlyList<SidebarItem> config, IReadOnlyList<SidebarEntry> entries)
    {
        ArgumentNullException.ThrowIfNull(config);
        ArgumentNullException.ThrowIfNull(entries);
        _config = config;
        _entries = entries;
    }

    /// <summary>
    /// Builds the resolved sidebar for the given current page path.
    /// </summary>
    /// <param name="currentPath">
    /// The path of the current page (e.g., <c>"/docs/guides/getting-started/"</c>).
    /// Used to mark the active item and expand ancestor groups.
    /// </param>
    /// <returns>The resolved top-level sidebar items.</returns>
    public IReadOnlyList<ResolvedSidebarItem> Build(string currentPath)
    {
        ArgumentNullException.ThrowIfNull(currentPath);
        return ResolveItems(_config, currentPath);
    }

    private IReadOnlyList<ResolvedSidebarItem> ResolveItems(
        IReadOnlyList<SidebarItem> items,
        string currentPath)
    {
        var resolved = new List<ResolvedSidebarItem>(items.Count);
        foreach (var item in items)
        {
            resolved.Add(ResolveItem(item, currentPath));
        }

        return resolved;
    }

    private ResolvedSidebarItem ResolveItem(SidebarItem item, string currentPath)
    {
        // Leaf link item
        if (item.Link is not null)
        {
            var isCurrent = IsCurrent(item.Link, currentPath);
            return new ResolvedSidebarItem(item.Label, item.Link, isCurrent, item.Badge);
        }

        // Auto-generate group
        if (item.AutoGenerate is not null)
        {
            return ResolveAutoGeneratedGroup(item, currentPath);
        }

        // Manual group with children
        var children = ResolveItems(item.Items, currentPath);
        var isActive = children.Any(c => c.IsActive);
        return new ResolvedSidebarItem(item.Label, isActive, item.Badge, item.Collapsed, children);
    }

    private ResolvedSidebarItem ResolveAutoGeneratedGroup(SidebarItem item, string currentPath)
    {
        var dir = item.AutoGenerate!;
        var normalizedDir = dir.Trim('/');

        // Find all entries whose slug starts with the given directory prefix.
        var matching = _entries
            .Where(e => SlugMatchesDirectory(e.Slug, normalizedDir))
            .OrderBy(e => e.Order)
            .ThenBy(e => e.Label, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var children = matching
            .Select(e => new ResolvedSidebarItem(e.Label, e.Href, IsCurrent(e.Href, currentPath), e.Badge))
            .ToList();

        var isActive = children.Any(c => c.IsActive);
        return new ResolvedSidebarItem(item.Label, isActive, item.Badge, item.Collapsed, children);
    }

    /// <summary>
    /// Returns a flattened ordered list of all link items (no group headers) from the resolved sidebar.
    /// Useful for pagination resolution.
    /// </summary>
    /// <param name="items">The resolved sidebar items to flatten.</param>
    /// <returns>All leaf link items in sidebar order.</returns>
    public static IReadOnlyList<ResolvedSidebarItem> Flatten(IReadOnlyList<ResolvedSidebarItem> items)
    {
        ArgumentNullException.ThrowIfNull(items);
        var result = new List<ResolvedSidebarItem>();
        FlattenInto(items, result);
        return result;
    }

    private static void FlattenInto(IReadOnlyList<ResolvedSidebarItem> items, List<ResolvedSidebarItem> result)
    {
        foreach (var item in items)
        {
            if (item.IsGroup)
            {
                FlattenInto(item.Items, result);
            }
            else
            {
                result.Add(item);
            }
        }
    }

    private static bool SlugMatchesDirectory(string slug, string normalizedDir)
    {
        if (string.IsNullOrEmpty(normalizedDir))
        {
            return true; // empty dir = all entries
        }

        var normalizedSlug = slug.Replace('\\', '/');
        return normalizedSlug.Equals(normalizedDir, StringComparison.OrdinalIgnoreCase) ||
               normalizedSlug.StartsWith(normalizedDir + "/", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsCurrent(string href, string currentPath)
    {
        // Normalize trailing slash for comparison.
        var normalizedHref = href.TrimEnd('/');
        var normalizedCurrent = currentPath.TrimEnd('/');
        return string.Equals(normalizedHref, normalizedCurrent, StringComparison.OrdinalIgnoreCase);
    }
}
